<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PWSmoke</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>de45b05b-efa8-4e48-81df-e89788815175</testSuiteGuid>
   <testCaseLink>
      <guid>cb339c9c-5667-41c5-88b6-e0adacb411a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CSPW/PW SMOKE/VerifyDashBoardPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76c9bb73-bd3d-4142-a8b0-2339eb5c586b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f6d896-253a-48db-821c-a94823a4b68b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22cc813f-25a8-42d4-8dd8-ae73e99eac43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c3b05c5-f83c-42b1-ac74-b0caa6090abb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1f45468-ccef-44d0-b3c7-f3cb98b96118</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CSPW/PW SMOKE/VerifyLoginLogout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ac9e34f0-5bb0-419e-9e87-9e411fcdf54d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CSPW/PW SMOKE/VerifyViewOrder</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
