<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_MenuStyle</name>
   <tag></tag>
   <elementGuidId>d621874d-6007-4130-83b9-a73b9c301b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//span[@id='ctl00_Body_GexDropDown03_ItemEditor_Arrow']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
