<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InsertLink</name>
   <tag></tag>
   <elementGuidId>6620ed5c-b078-4553-9b90-daf4062456bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='ctl00_ctl00_cphMain_cphMain_gvNotificationGroups_ctl01_btnInsert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
