<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//*[@id='btnEditSelected']</description>
   <name>btnAddtoProgram</name>
   <tag></tag>
   <elementGuidId>27bfd60a-471f-4b12-9d32-44c79e98441e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='btnEditSelected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
