<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//*[@id='btnDeleteElement']</description>
   <name>btnDelete</name>
   <tag></tag>
   <elementGuidId>2a050b39-4a93-43b2-b45d-efbed2bfea0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='btndelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
