<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EstVerToolTip</name>
   <tag></tag>
   <elementGuidId>b3f75593-6d9b-4a71-bd0a-8e40f9cf59e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='allProgramsList_wrapper']/table/tbody/preceding-sibling::thead/tr/th[5]/a/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
