<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DiscontinousOption</name>
   <tag></tag>
   <elementGuidId>2e8ca7d1-2a62-4976-baf8-f0fd760528b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='ctl00_MainContent_rwDeleteItemSettings_C_radItemAdjType_DropDown']/div/ul/li[11]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
