<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>APPLICATIONADMINISTRATIONmenuTab</name>
   <tag></tag>
   <elementGuidId>de02fac2-677a-4a43-a461-22a4e89dd7a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='ctl00_ctl00_cphMainMenu_telMenuTop']/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
