<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderPackListLink</name>
   <tag></tag>
   <elementGuidId>fce946f1-3398-4ca9-9b55-753e30305621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='ctl00_MainContent_rdQuickLinks_C_QuickOrderSearch1_rmQuickLinks']/ul/li[10]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
