<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>salesProdLineKey</name>
   <tag></tag>
   <elementGuidId>8bf0265a-9f43-4298-b8d4-684fab1d64c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='ctl00_Body_fvShippingAgentRules_ddlSalesProdLineKey']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
