<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveSelected</name>
   <tag></tag>
   <elementGuidId>46f732ac-08e8-4d5e-8397-9da5a414b872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cphMain_cphMain_btnSave</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='cphMain_cphMain_btnbulksave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
